# Import libraries

In [6]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


Load Data

In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Build a machine learning model

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.00904492,  0.43948752, -0.47814366,  0.46443957,  0.08528481,
         0.6548442 , -0.88279235,  0.78978455,  0.27692074,  0.29617974]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.07594912, 0.11893725, 0.04751117, 0.1219423 , 0.08346216,
        0.14751837, 0.03169999, 0.16883013, 0.10109182, 0.10305762]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

1.9138026

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2962 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1418 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1071 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0889 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0754 - accuracy: 0.9761


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0755 - accuracy: 0.9758 - 978ms/epoch - 3ms/step


[0.0755050927400589, 0.9757999777793884]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.4085484e-08, 3.2327605e-08, 7.8759820e-07, 3.2586255e-04,
        1.4236924e-10, 8.4331326e-08, 2.2573263e-15, 9.9967074e-01,
        4.8477585e-08, 2.4742367e-06],
       [1.1306552e-09, 2.4694030e-04, 9.9973589e-01, 1.1566967e-05,
        1.1706480e-15, 9.6566019e-08, 2.2995126e-09, 6.0243108e-13,
        5.4924726e-06, 2.0135931e-13],
       [5.6900930e-08, 9.9975520e-01, 1.7614057e-05, 5.5578957e-06,
        6.1766386e-06, 1.1767406e-06, 4.7980739e-06, 9.7109587e-05,
        1.1145440e-04, 9.6283964e-07],
       [9.9998617e-01, 4.6268411e-09, 5.2971550e-06, 4.2290836e-08,
        2.2378103e-07, 3.1575905e-06, 3.5474293e-06, 5.3350487e-07,
        5.0807405e-08, 1.0633534e-06],
       [1.6581102e-05, 5.2838573e-08, 4.9452388e-05, 3.8816583e-07,
        9.8992026e-01, 2.1843755e-06, 7.7557939e-07, 8.6156192e-04,
        1.5499212e-05, 9.1331890e-03]], dtype=float32)>